_common/lib: !include "../../package-common.yaml"

name:                hs-opentelemetry-instrumentation-yesod
version:             0.1.1.0

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Yesod middleware for providing OpenTelemetry instrumentation
category:            OpenTelemetry, Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/instrumentation/yesod#readme>

dependencies:
- base >= 4.7 && < 5

library:
  ghc-options: -Wall
  source-dirs: src
  dependencies:
  # instrumented library
  - yesod-core ^>= 1.6
  # opentelemetry dependencies
  - hs-opentelemetry-api ^>= 0.3
  - hs-opentelemetry-instrumentation-wai
  # external dependencies
  - microlens ^>= 0.4 || ^>= 0.5
  - template-haskell ^>= 2.21 || ^>= 2.22 || ^>= 2.23 || ^>= 2.24
  - text ^>= 2
  - unliftio ^>= 0.2
  - unordered-containers ^>= 0.2
  - wai ^>= 3.2

# Test suite not yet implemented
_tests:
  hs-opentelemetry-instrumentation-yesod-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    # package under test
    - hs-opentelemetry-instrumentation-yesod
