_common/lib: !include "../../package-common.yaml"

name:                hs-opentelemetry-instrumentation-wai
version:             0.1.1.0

<<: *preface

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            WAI instrumentation middleware for OpenTelemetry
category:            OpenTelemetry, Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iand675/hs-opentelemetry/tree/main/instrumentation/wai#readme>

dependencies:
- base >= 4.7 && < 5

library:
  ghc-options: -Wall
  source-dirs: src
  dependencies:
  # instrumented library
  - wai ^>= 3.2
  # opentelemetry dependencies
  - hs-opentelemetry-api ^>= 0.3
  # external dependencies
  - http-types ^>= 0.12
  - iproute ^>= 1.7
  - network ^>= 3.2
  - text ^>= 2
  - unordered-containers ^>= 0.2
  - vault ^>= 0.3

# Test suite not yet implemented
_tests:
  hs-opentelemetry-instrumentation-wai-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    # package under test
    - hs-opentelemetry-instrumentation-wai
